from .node import NODE_CLASS_MAPPINGS as BASE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BASE_DISPLAY_MAPPINGS
from .power_lora_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_MAPPINGS
from .power_lora_stacker import NODE_CLASS_MAPPINGS as STACKER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STACKER_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**BASE_MAPPINGS, **LOADER_MAPPINGS, **STACKER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BASE_DISPLAY_MAPPINGS, **LOADER_DISPLAY_MAPPINGS, **STACKER_DISPLAY_MAPPINGS}

# 导出必要的映射，让 ComfyUI 能够识别自定义节点
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

# 告诉 ComfyUI 当前目录有 web 资源（JS 文件）
WEB_DIRECTORY = "."